### ISSUE TITLE
Items are considered in position before they have been animated to move there

### ISSUE THREAD

**Issue by carlnewton** [carlnewton/rover#12]
A rethink of `Move.js` is needed. It exists to queue movements so that if the player (and potentially anything else on the map) was to quickly move up then left, for instance, the animation would not chop away from the first movement to the second. But the solution I have put in place causes a few issues:

- Pushing a block many moves into the future moves the block before the player has visually been positioned to move it.
- There is no limit to the amount of items in a queue, which can cause a visual lag type effect

**Comment by carlnewton** [comment]
Thanks @mikedevelops I can definitely see this being useful for collisions, but I don't believe that it resolves this issue.

It's a lot easier to see this issue when we slow the player speed down. If the player is at tile `0`, and a block at tile `3`:

```
|0|1|2|3|4|
|P| | |B| |
```

At the moment, if the player was instructed to move right three times, the end result would be as follows:

```
|0|1|2|3|4|
| | | |P|B|
```

Which is correct, however, because the speed of the player is not factored in to its current position, the block appears to move before the player reaches it. In animation, it looks like this:
```
|0|1|2|3|4|
|P| | |B| |
| |P| | |B|
| | |P| |B|
| | | |P|B|
```

The block can predict the future!

This is because [moving the player is determined by whether or not the block it attempted to push successfully moved](https://github.com/carlnewton/rover/blob/master/src/Player.js#L20), and then [the new position of the player is set once the Move entry is added](https://github.com/carlnewton/rover/blob/master/src/Player.js#L22). Ideally, this new position will be set at the successful execution of a Move entry, but the problem with this is that the `fromRow`, `fromCell`, `toRow` and `toCell` values are skewed when changing the order of execution.

I was thinking of changing the `toRow` and `toCell` to `direction` to simplify this. ie, we have the exact location of the player, and they want to move `up` from that position.

**Comment by mikedevelops** [comment]
Thank you for the explanation, that makes it a lot clearer. I think in the case where you have this movement queue / input buffer, you'll need to resolve collision (I'm classing pushing a box here as a collision) based on the players actual position. Otherwise (stating the obvious) if you introduce entities that are not static, it'll be really tricky to determine if they will collide.

Although it might be tricker / more fun (😄) to introduce a more physics'y physics engine that is relative to speed, I think it'll be essential once you start to introduce other things that can move.

**Comment by mikedevelops** [comment]
One way might be to iterate your `tick` function to include a delta / ms since last frame (so the players speed is not relative to the frame rate) and then the players movement would be perhaps something like (pseudo code)

```
move (Vector2 target, number delta) {
    this.moveTowards(target, this.speed * delta);

    if (this.positionToCell(this.position) === target) { // we are there }
}

```

**Comment by mikedevelops** [comment]
I think you either have to remove animation, so your collision can be resolved using the current method. Or keep animations and treat the players position as something that can be in-between the grid and resolve collisions based on their actual position.

**Comment by carlnewton** [comment]
Thanks for pointing me in the right direction on this @mikedevelops. I don't think I've handled collisions quite as well as you've described here, but I have resolved this bug by introducing delta time and querying if a block exists on a tile or if it's about to exist on a tile.

Thanks again :D
